<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260327000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create usuarios table for authentication';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles TEXT NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_95316B44E7927C74 ON usuarios (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE usuarios');
    }
}
